description: >-
  Discussion of the Low-Level Versioned Store (LLVS) and
  other aspects of distributed data storage.
baseurl: "/LLVS" 
url: "https://mentalfaculty.github.io"

theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-feed

title: LLVS Blog
twitter_username: drewmccormack
github_username:  mentalfaculty
